<a href="https://colab.research.google.com/github/omkarpattnaik8080/DataScienceRevision/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]


In [3]:
ar=np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
#another way of converting list into an array
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
#matrix(bydefault 2d)
b=np.asmatrix(l)

In [8]:
b

matrix([[1, 2, 3, 4, 5]])

In [9]:
a=np.array(l)

In [10]:
c=a

In [11]:
c

array([1, 2, 3, 4, 5])

In [12]:
c[0]=100

In [13]:
c

array([100,   2,   3,   4,   5])

In [14]:
d=np.copy(a)

In [15]:
d

array([100,   2,   3,   4,   5])

In [16]:
a[1]=400

In [17]:
a

array([100, 400,   3,   4,   5])

In [18]:
d

array([100,   2,   3,   4,   5])

In [19]:
#conversion of string to array
np.fromstring('234 567',sep=' ')

array([234., 567.])

In [20]:
#Numpy Datatypes
l=[2,3,4,5,6]
ar=np.array(l)

In [21]:
ar

array([2, 3, 4, 5, 6])

In [22]:
ar.ndim

1

In [23]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [24]:
ar2.ndim

2

In [25]:
ar.size

5

In [26]:
ar2.size

8

In [27]:
ar.shape

(5,)

In [28]:
ar2.shape

(2, 4)

In [30]:
ar.dtype

dtype('int64')

In [36]:
list=range(5)

In [37]:
list

range(0, 5)

In [38]:
#in numpy we can give floating point as a range
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [39]:
np.linspace(1,5,10)#producing 10 datas between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [41]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [42]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [43]:
arr4=np.zeros((3,4,2,3))

In [45]:
arr4.ndim

4

In [46]:
np.ones(4)

array([1., 1., 1., 1.])

In [54]:
on=np.ones((2,3))

In [55]:
on+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [56]:
on

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.empty((3,5))

array([[4.72327828e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.52322726e-310],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05162714e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.32404027e-322]])

In [58]:
#for identifty matrix we can use eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [61]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [63]:
arr=np.random.randn(3,4)

In [64]:
import pandas as pd

In [65]:
pd.DataFrame(arr)

0         1         2         3
0 -0.783718  0.347447  0.634206  1.242047
1  0.182895 -0.024668  0.165632  0.277514
2 -0.960226 -0.621483  0.227104  0.631121

In [66]:
np.random.rand(3,4)

array([[0.11950347, 0.23312226, 0.42491869, 0.39889412],
       [0.6883333 , 0.01362655, 0.31775752, 0.57719795],
       [0.02719692, 0.74541818, 0.86377023, 0.27975098]])

In [68]:
np.random.randint(1,110,(3,4)) #khali integer values deta hai

array([[ 44,  18,  84,  69],
       [  2, 103,  13,  50],
       [ 40,  11,  47,  87]])

In [69]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [70]:
arr=np.random.rand(3,4)

In [71]:
arr

array([[0.42739211, 0.97059471, 0.57936955, 0.40222586],
       [0.53927065, 0.82026685, 0.38888683, 0.83553374],
       [0.69509858, 0.61278485, 0.06386548, 0.79346434]])

In [73]:
arr.reshape(6,2)

array([[0.42739211, 0.97059471],
       [0.57936955, 0.40222586],
       [0.53927065, 0.82026685],
       [0.38888683, 0.83553374],
       [0.69509858, 0.61278485],
       [0.06386548, 0.79346434]])

In [74]:
arr[1][1]

0.8202668460180326

In [78]:
arr[2:3,1]

array([0.61278485])

In [80]:
arr=np.random.randint(1,100,(50,50))

In [81]:
arr

array([[93, 17, 75, ..., 35, 34, 41],
       [12, 59, 17, ..., 86, 20,  4],
       [89, 44, 48, ..., 12, 91, 87],
       ...,
       [36, 33, 48, ..., 98, 59, 50],
       [86, 76, 46, ..., 17, 86, 15],
       [97, 44, 31, ..., 33, 76, 69]])

In [83]:
arr[arr>50]

array([93, 75, 73, ..., 64, 76, 69])

In [84]:
arr

array([[93, 17, 75, ..., 35, 34, 41],
       [12, 59, 17, ..., 86, 20,  4],
       [89, 44, 48, ..., 12, 91, 87],
       ...,
       [36, 33, 48, ..., 98, 59, 50],
       [86, 76, 46, ..., 17, 86, 15],
       [97, 44, 31, ..., 33, 76, 69]])

In [85]:
arr[2:4,[1,2]]

array([[44, 48],
       [77, 37]])

In [86]:
arr[0][0]=5000

In [87]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [88]:
arr1

array([[2, 1, 2],
       [1, 2, 2],
       [1, 1, 1]])

In [89]:
arr2

array([[2, 1, 1],
       [1, 1, 2],
       [2, 1, 1]])

In [90]:
arr1+arr2

array([[4, 2, 3],
       [2, 3, 4],
       [3, 2, 2]])

In [91]:
arr1/arr2

array([[1. , 1. , 2. ],
       [1. , 2. , 1. ],
       [0.5, 1. , 1. ]])

In [92]:
arr1*arr2

array([[4, 1, 2],
       [1, 2, 4],
       [2, 1, 1]])

In [93]:
arr1@arr2

array([[9, 5, 6],
       [8, 5, 7],
       [5, 3, 4]])

In [94]:
arr1/0

<ipython-input-94-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [95]:
#numpy broadcasting
arr=np.zeros((4,4))

In [96]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [98]:
row=np.array([1,2,3,4])

In [99]:
row.shape

(4,)

In [100]:
np.sqrt(arr1)

array([[1.41421356, 1.        , 1.41421356],
       [1.        , 1.41421356, 1.41421356],
       [1.        , 1.        , 1.        ]])

In [101]:
#array manipulation
arr=np.random.randint(1,10,(3,4))

In [102]:
arr

array([[8, 6, 1, 6],
       [5, 6, 9, 5],
       [5, 1, 7, 1]])

In [103]:
arr.reshape(6,2)

array([[8, 6],
       [1, 6],
       [5, 6],
       [9, 5],
       [5, 1],
       [7, 1]])

In [104]:
arr.T

array([[8, 5, 5],
       [6, 6, 1],
       [1, 9, 7],
       [6, 5, 1]])

In [105]:
arr

array([[8, 6, 1, 6],
       [5, 6, 9, 5],
       [5, 1, 7, 1]])

In [107]:
arr.flatten() #conversion to 1d

array([8, 6, 1, 6, 5, 6, 9, 5, 5, 1, 7, 1])

In [108]:
arr.ndim

2

In [109]:
np.expand_dims(arr,axis=1)

array([[[8, 6, 1, 6]],

       [[5, 6, 9, 5]],

       [[5, 1, 7, 1]]])

In [110]:
np.expand_dims(arr,axis=0)

array([[[8, 6, 1, 6],
        [5, 6, 9, 5],
        [5, 1, 7, 1]]])

In [112]:
np.squeeze(arr)

array([[8, 6, 1, 6],
       [5, 6, 9, 5],
       [5, 1, 7, 1]])

In [113]:
data=np.array([[1],[2],[3]])

In [114]:
data

array([[1],
       [2],
       [3]])

In [115]:
np.squeeze(data)

array([1, 2, 3])

In [116]:
np.repeat(arr,3)

array([8, 8, 8, 6, 6, 6, 1, 1, 1, 6, 6, 6, 5, 5, 5, 6, 6, 6, 9, 9, 9, 5,
       5, 5, 5, 5, 5, 1, 1, 1, 7, 7, 7, 1, 1, 1])

In [117]:
np.roll(arr,2)

array([[7, 1, 8, 6],
       [1, 6, 5, 6],
       [9, 5, 5, 1]])