<a href="https://colab.research.google.com/github/omkarpattnaik8080/DataScienceRevision/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
l=[1,2,3,4,5]


In [3]:
ar=np.array(l)

In [4]:
type(ar)

numpy.ndarray

In [5]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [6]:
#another way of converting list into an array
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
#matrix(bydefault 2d)
b=np.asmatrix(l)

In [8]:
b

matrix([[1, 2, 3, 4, 5]])

In [9]:
a=np.array(l)

In [10]:
c=a

In [11]:
c

array([1, 2, 3, 4, 5])

In [12]:
c[0]=100

In [13]:
c

array([100,   2,   3,   4,   5])

In [14]:
d=np.copy(a)

In [15]:
d

array([100,   2,   3,   4,   5])

In [16]:
a[1]=400

In [17]:
a

array([100, 400,   3,   4,   5])

In [18]:
d

array([100,   2,   3,   4,   5])

In [19]:
#conversion of string to array
np.fromstring('234 567',sep=' ')

array([234., 567.])

In [20]:
#Numpy Datatypes
l=[2,3,4,5,6]
ar=np.array(l)

In [21]:
ar

array([2, 3, 4, 5, 6])

In [22]:
ar.ndim

1

In [23]:
ar2=np.array([[1,2,3,4],[2,3,4,5]])

In [24]:
ar2.ndim

2

In [25]:
ar.size

5

In [26]:
ar2.size

8

In [27]:
ar.shape

(5,)

In [28]:
ar2.shape

(2, 4)

In [29]:
ar.dtype

dtype('int64')

In [30]:
list=range(5)

In [31]:
list

range(0, 5)

In [32]:
#in numpy we can give floating point as a range
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [33]:
np.linspace(1,5,10)#producing 10 datas between 1 and 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [34]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [35]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [36]:
arr4=np.zeros((3,4,2,3))

In [37]:
arr4.ndim

4

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [39]:
on=np.ones((2,3))

In [40]:
on+5

array([[6., 6., 6.],
       [6., 6., 6.]])

In [41]:
on

array([[1., 1., 1.],
       [1., 1., 1.]])

In [42]:
np.empty((3,5))

array([[4.90596364e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 1.60219034e-306],
       [1.50008929e+248, 4.31174539e-096, 9.80058441e+252,
        1.23971686e+224, 1.05235435e-153],
       [9.03292329e+271, 9.08366793e+223, 1.06244660e-153,
        3.44981369e+175, 6.32404027e-322]])

In [43]:
#for identifty matrix we can use eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [45]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [46]:
arr=np.random.randn(3,4)

In [47]:
import pandas as pd

In [48]:
pd.DataFrame(arr)

0         1         2         3
0  0.782233  0.778024  0.849548 -0.481302
1  0.902407 -0.341137  0.469071  1.230770
2  1.773249 -0.120408 -0.111861 -0.314003

In [49]:
np.random.rand(3,4)

array([[0.29774746, 0.58553919, 0.63986432, 0.19548927],
       [0.66227124, 0.4594712 , 0.59456095, 0.9325658 ],
       [0.86177264, 0.23208252, 0.38504286, 0.27529817]])

In [50]:
np.random.randint(1,110,(3,4)) #khali integer values deta hai

array([[ 49,  27,   9,  35],
       [ 35,  85,   1, 109],
       [ 29,  55,  87,  59]])

In [51]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [52]:
arr=np.random.rand(3,4)

In [53]:
arr

array([[0.67413822, 0.74028545, 0.40867456, 0.16609627],
       [0.59644316, 0.49310562, 0.34188113, 0.51347606],
       [0.70619377, 0.43378966, 0.92811075, 0.69861715]])

In [54]:
arr.reshape(6,2)

array([[0.67413822, 0.74028545],
       [0.40867456, 0.16609627],
       [0.59644316, 0.49310562],
       [0.34188113, 0.51347606],
       [0.70619377, 0.43378966],
       [0.92811075, 0.69861715]])

In [55]:
arr[1][1]

0.49310561894820426

In [56]:
arr[2:3,1]

array([0.43378966])

In [57]:
arr=np.random.randint(1,100,(50,50))

In [58]:
arr

array([[13, 38, 33, ...,  9, 20, 59],
       [72, 49, 79, ..., 42, 74, 31],
       [43, 20,  7, ..., 63, 53, 80],
       ...,
       [35, 72,  2, ..., 12, 96, 85],
       [57, 18, 65, ..., 12,  8, 51],
       [50, 76, 98, ..., 35, 98, 59]])

In [59]:
arr[arr>50]

array([53, 69, 73, ..., 60, 98, 59])

In [60]:
arr

array([[13, 38, 33, ...,  9, 20, 59],
       [72, 49, 79, ..., 42, 74, 31],
       [43, 20,  7, ..., 63, 53, 80],
       ...,
       [35, 72,  2, ..., 12, 96, 85],
       [57, 18, 65, ..., 12,  8, 51],
       [50, 76, 98, ..., 35, 98, 59]])

In [61]:
arr[2:4,[1,2]]

array([[20,  7],
       [70, 18]])

In [62]:
arr[0][0]=5000

In [65]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [66]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [1, 1, 2]])

In [67]:
arr2

array([[2, 2, 1],
       [1, 1, 2],
       [1, 2, 1]])

In [68]:
arr1+arr2

array([[4, 4, 2],
       [3, 3, 4],
       [2, 3, 3]])

In [69]:
arr1/arr2

array([[1. , 1. , 1. ],
       [2. , 2. , 1. ],
       [1. , 0.5, 2. ]])

In [70]:
arr1*arr2

array([[4, 4, 1],
       [2, 2, 4],
       [1, 2, 2]])

In [71]:
arr1@arr2

array([[ 7,  8,  7],
       [ 8, 10,  8],
       [ 5,  7,  5]])

In [72]:
arr1/0

<ipython-input-72-2e1dc0d9289f>:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [73]:
#numpy broadcasting
arr=np.zeros((4,4))

In [74]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [75]:
row=np.array([1,2,3,4])

In [76]:
row.shape

(4,)

In [77]:
np.sqrt(arr1)

array([[1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.41421356]])

In [78]:
#array manipulation
arr=np.random.randint(1,10,(3,4))

In [79]:
arr

array([[4, 7, 4, 9],
       [5, 2, 9, 8],
       [8, 5, 2, 6]])

In [80]:
arr.reshape(6,2)

array([[4, 7],
       [4, 9],
       [5, 2],
       [9, 8],
       [8, 5],
       [2, 6]])

In [81]:
arr.T

array([[4, 5, 8],
       [7, 2, 5],
       [4, 9, 2],
       [9, 8, 6]])

In [82]:
arr

array([[4, 7, 4, 9],
       [5, 2, 9, 8],
       [8, 5, 2, 6]])

In [83]:
arr.flatten() #conversion to 1d

array([4, 7, 4, 9, 5, 2, 9, 8, 8, 5, 2, 6])

In [84]:
arr.ndim

2

In [85]:
np.expand_dims(arr,axis=1)

array([[[4, 7, 4, 9]],

       [[5, 2, 9, 8]],

       [[8, 5, 2, 6]]])

In [86]:
np.expand_dims(arr,axis=0)

array([[[4, 7, 4, 9],
        [5, 2, 9, 8],
        [8, 5, 2, 6]]])

In [87]:
np.squeeze(arr)

array([[4, 7, 4, 9],
       [5, 2, 9, 8],
       [8, 5, 2, 6]])

In [88]:
data=np.array([[1],[2],[3]])

In [89]:
data

array([[1],
       [2],
       [3]])

In [90]:
np.squeeze(data)

array([1, 2, 3])

In [91]:
np.repeat(arr,3)

array([4, 4, 4, 7, 7, 7, 4, 4, 4, 9, 9, 9, 5, 5, 5, 2, 2, 2, 9, 9, 9, 8,
       8, 8, 8, 8, 8, 5, 5, 5, 2, 2, 2, 6, 6, 6])

In [92]:
np.roll(arr,2)

array([[2, 6, 4, 7],
       [4, 9, 5, 2],
       [9, 8, 8, 5]])

In [93]:
np.roll(arr1,2)

array([[1, 2, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [94]:
arr1

array([[2, 2, 1],
       [2, 2, 2],
       [1, 1, 2]])

In [95]:
np.diag(arr1)

array([2, 2, 2])

In [96]:
arr1=np.random.randint(1,100,(3,4))

In [101]:
arr2=np.random.randint(1,100,(3,4))

In [102]:
arr1

array([[92, 69, 45, 74],
       [92, 24, 21, 47],
       [ 6,  3, 26, 57]])

In [103]:
arr1+arr2

array([[107, 144, 133, 107],
       [173,  34,  28, 131],
       [ 98,  56,  90,  85]])

In [104]:
arr1/arr2

array([[6.13333333, 0.92      , 0.51136364, 2.24242424],
       [1.13580247, 2.4       , 3.        , 0.55952381],
       [0.06521739, 0.05660377, 0.40625   , 2.03571429]])

In [105]:
arr1*arr2

array([[1380, 5175, 3960, 2442],
       [7452,  240,  147, 3948],
       [ 552,  159, 1664, 1596]])

In [106]:
arr1-arr2

array([[ 77,  -6, -43,  41],
       [ 11,  14,  14, -37],
       [-86, -50, -38,  29]])

In [107]:
arr1%arr2

array([[ 2, 69, 45,  8],
       [11,  4,  0, 47],
       [ 6,  3, 26,  1]])

In [108]:
arr1**arr2

array([[ 9109462399215206400, -6840376502709911907, -6246047054307494815,
        -5458429500754755584],
       [                   0,       63403380965376,           1801088541,
         5220961609757736513],
       [                   0, -2709163618235644365,                    0,
        -5595785634705148767]])

In [109]:
arr1 & arr2

array([[12, 65,  8,  0],
       [80,  8,  5,  4],
       [ 4,  1,  0, 24]])

In [110]:
~arr1

array([[-93, -70, -46, -75],
       [-93, -25, -22, -48],
       [ -7,  -4, -27, -58]])

In [111]:
arr1>arr2

array([[ True, False, False,  True],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [113]:
arr1<arr2

array([[False,  True,  True, False],
       [False, False, False,  True],
       [ True,  True,  True, False]])

In [114]:
#Numpy string functions

In [116]:
arr=np.array(['sudh','kumar'])

In [117]:
np.char.upper(arr)

array(['SUDH', 'KUMAR'], dtype='<U5')

In [118]:
np.char.title(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [119]:
np.char.capitalize(arr)

array(['Sudh', 'Kumar'], dtype='<U5')

In [120]:
arr1

array([[92, 69, 45, 74],
       [92, 24, 21, 47],
       [ 6,  3, 26, 57]])

In [121]:
np.sin(arr1)

array([[-0.77946607, -0.11478481,  0.85090352, -0.98514626],
       [-0.77946607, -0.90557836,  0.83665564,  0.12357312],
       [-0.2794155 ,  0.14112001,  0.76255845,  0.43616476]])

In [122]:
np.cos(arr1)

array([[-0.62644445,  0.99339038,  0.52532199,  0.17171734],
       [-0.62644445,  0.42417901, -0.54772926, -0.99233547],
       [ 0.96017029, -0.9899925 ,  0.64691932,  0.89986683]])

In [123]:
np.tanh(arr1)

array([[1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        ],
       [0.99998771, 0.99505475, 1.        , 1.        ]])

In [124]:
np.log10(arr1)

array([[1.96378783, 1.83884909, 1.65321251, 1.86923172],
       [1.96378783, 1.38021124, 1.32221929, 1.67209786],
       [0.77815125, 0.47712125, 1.41497335, 1.75587486]])

In [125]:
np.sqrt(arr1)

array([[9.59166305, 8.30662386, 6.70820393, 8.60232527],
       [9.59166305, 4.89897949, 4.58257569, 6.8556546 ],
       [2.44948974, 1.73205081, 5.09901951, 7.54983444]])

In [127]:
np.power(arr1,2)

array([[8464, 4761, 2025, 5476],
       [8464,  576,  441, 2209],
       [  36,    9,  676, 3249]])

In [128]:
np.mean(arr1)

46.333333333333336

In [129]:
np.median(arr1)

46.0

In [130]:
np.std(arr1)

29.755485021906278

In [131]:
np.min(arr1)

3

In [132]:
np.max(arr1)

92

In [133]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,18])

In [135]:
np.sort(arr)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 18])

In [138]:
np.searchsorted(arr,35)

15

In [139]:
np.count_nonzero(arr)

15

In [140]:
np.where(arr>6)

(array([ 6,  7,  8,  9, 10, 11, 12, 13, 14]),)

In [141]:
np.extract(arr>6,arr)

array([ 7,  8,  9, 10, 11, 12, 13, 14, 18])

In [146]:
#numpy:byte swapping
arr.byteswap()

array([  72057594037927936,  144115188075855872,  216172782113783808,
        288230376151711744,  360287970189639680,  432345564227567616,
        504403158265495552,  576460752303423488,  648518346341351424,
        720575940379279360,  792633534417207296,  864691128455135232,
        936748722493063168, 1008806316530991104, 1297036692682702848])

In [147]:
#Numpy -- Copy & Views
a=np.copy(arr1)

In [148]:
b=arr1.view()

In [149]:
b=arr

In [150]:
import numpy.matlib as nm

In [151]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [152]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [153]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [154]:
# Numpy - Linear Algebra
arr1=np.random.randint([[2,3],[4,5]])
arr2=np.random.randint([[5,3],[2,5]])

In [155]:
np.dot(arr1,arr2)

array([[2, 5],
       [3, 8]])

In [156]:
arr1@arr2

array([[2, 5],
       [3, 8]])