<a href="https://colab.research.google.com/github/omkarpattnaik8080/DataScienceRevision/blob/main/SVMRegressor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt


In [2]:
#Sythetic dataset
from sklearn.datasets import make_classification

In [3]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42)

In [4]:
X

array([[ 0.96479937, -0.06644898,  0.98676805, ..., -1.2101605 ,
        -0.62807677,  1.22727382],
       [-0.91651053, -0.56639459, -1.00861409, ..., -0.98453405,
         0.36389642,  0.20947008],
       [-0.10948373, -0.43277388, -0.4576493 , ..., -0.2463834 ,
        -1.05814521, -0.29737608],
       ...,
       [ 1.67463306,  1.75493307,  1.58615382, ...,  0.69272276,
        -1.50384972,  0.22526412],
       [-0.77860873, -0.83568901, -0.19484228, ..., -0.49735437,
         2.47213818,  0.86718741],
       [ 0.24845351, -1.0034389 ,  0.36046013, ...,  0.77323999,
         0.1857344 ,  1.41641179]])

In [5]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1,

In [8]:
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=42,weights=[0.9,0.1])

In [10]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [11]:
from sklearn.svm import SVR

In [12]:
svr=SVR(kernel='linear')

In [13]:
svr.fit(X_train,y_train)

SVR(kernel='linear')

In [14]:
svr.coef_

array([[-0.01734257,  0.00275367, -0.02297649,  0.00332184, -0.00106902,
         0.00010278,  0.0450432 ,  0.00399237, -0.00582763,  0.00028861]])

In [15]:
y_pred=svr.predict(X_test)

In [16]:
y_pred

array([ 0.06211248,  0.06233297,  0.11861527,  0.17485999,  0.03410482,
        0.22079401,  0.00819925,  0.04905387,  0.05458807,  0.09786734,
        0.05101021,  0.07443366,  0.11865879,  0.08525155,  0.15264582,
        0.06790329,  0.06433697,  0.09343845,  0.01635626,  0.03104407,
        0.09809963,  0.01964877,  0.080327  ,  0.08377826,  0.06211345,
        0.07208559,  0.16786755,  0.05710067,  0.12988783,  0.05725172,
        0.06431201, -0.09682824,  0.0428435 ,  0.03619657,  0.04400512,
        0.08932069,  0.16447775,  0.14661096,  0.11520891, -0.09947103,
        0.02345036,  0.03678346,  0.12007572,  0.04744322,  0.00389438,
        0.09846804,  0.04804004,  0.04356605,  0.00583073,  0.06227418,
        0.07229137,  0.06168984,  0.09114033,  0.09798235,  0.0848135 ,
        0.08790536,  0.07990899,  0.02009695,  0.05433275,  0.05300746,
        0.24049292,  0.08557802,  0.08363305,  0.00654987,  0.13207158,
        0.00868792,  0.09950444,  0.04664068,  0.07337037,  0.04

In [18]:
from sklearn.metrics import r2_score

In [19]:
print(r2_score(y_test,y_pred))

0.15013395613455616
